[package]
name = "rookiecodes/wind-system"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
WindShake = "rookie-codes/windshake@0.1.7"
WindLines = "rookie-codes/windlines@0.1.7"
